### ISSUE TITLE
confusing failure mode when the Manifest in the HEAD commit is screwed up

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaLang/Pkg.jl#1180]
See [this post](https://discourse.julialang.org/t/pkg-codetracking-not-found/23739) in discourse.

What happened was that I mistakenly broke my `Manifest.toml` when attempting to merge branches in git and edit the diff.  Once I had done this, I would get the error
```
ERROR: KeyError: key "CodeTracking" not found
Stacktrace:
 [1] getindex(::Dict{String,Any}, ::String) at ./dict.jl:478
 [2] Dict{Base.UUID,Pkg.Types.PackageEntry}(::Dict{String,Any}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:519
 [3] #read_manifest#47(::Nothing, ::Function, ::Base.GenericIOBuffer{Array{UInt8,1}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:571
 [4] read_manifest at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:559 [inlined]
 [5] (::getfield(Pkg.Display, Symbol("##4#15")){Pkg.Types.EnvCache})(::LibGit2.GitRepo) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Display.jl:73
 [6] with(::getfield(Pkg.Display, Symbol("##4#15")){Pkg.Types.EnvCache}, ::LibGit2.GitRepo) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LibGit2/src/types.jl:1125
 [7] #status#2(::Pkg.Types.PackageMode, ::Bool, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Display.jl:68
 [8] #status at ./none:0 [inlined]
 [9] #status#70(::Pkg.Types.PackageMode, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:484
 [10] (::getfield(Pkg.API, Symbol("#kw##status")))(::NamedTuple{(:mode,),Tuple{Pkg.Types.PackageMode}}, ::typeof(Pkg.API.status), ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at ./none:0
 [11] do_status!(::Dict{Symbol,Any}, ::Array{Pkg.Types.PackageSpec,1}, ::Dict{Symbol,Any}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:603
 [12] #invokelatest#1(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Any, ::Any, ::Vararg{Any,N} where N) at ./essentials.jl:742
 [13] invokelatest(::Any, ::Any, ::Vararg{Any,N} where N) at ./essentials.jl:741
 [14] do_cmd!(::Pkg.REPLMode.PkgCommand, ::REPL.LineEditREPL) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:561
 [15] #do_cmd#30(::Bool, ::Function, ::REPL.LineEditREPL, ::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:536
 [16] do_cmd at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:532 [inlined]
 [17] (::getfield(Pkg.REPLMode, Symbol("##48#51")){REPL.LineEditREPL,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:967
 [18] #invokelatest#1 at ./essentials.jl:742 [inlined]
 [19] invokelatest at ./essentials.jl:741 [inlined]
 [20] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/REPL/src/LineEdit.jl:2273
 [21] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:1035
 [22] run_repl(::REPL.AbstractREPL, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:192
 [23] (::getfield(Base, Symbol("##734#736")){Bool,Bool,Bool,Bool})(::Module) at ./client.jl:362
 [24] #invokelatest#1 at ./essentials.jl:742 [inlined]
 [25] invokelatest at ./essentials.jl:741 [inlined]
 [26] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:346
 [27] exec_options(::Base.JLOptions) at ./client.jl:284
 [28] _start() at ./client.jl:436
```
whenever I'd do `]status`.  I then got pretty thoroughly confused before I realized what was going on because nothing I did to change the `Manifest.toml` or `Project.toml` or even `.julia` seemed to fix it.  From a user perspective the error is caused by a "hidden" global state which is broken.

It would be nice if there were a more elegant failure mode for this sort of thing.

**Comment by oxinabox** [comment]
Same thing applies if you have problems with the Project.toml on head.
I had duplicates do to bad rebase, then when i was fixing them afterwards I wanted to make sure everything was right before i committed.
And I was like "Why does Pkg keep saying I have duplicates? I fixed those."

The trivial fix is that if there is an error when loading the git HEAD Manifest or Project
display a warning and then treat it as if it was an empty file. 

More broadly though I kind of think `Pkg.status` should be two commands.
One that just tells you the current state of everything, (what I normally want)
and one that tells you what has changed (what `Pkg.status` currently does)

**Comment by 00vareladavid** [comment]
@ExpandingMan Would you happen to still have the corrupted manifest file? I'm pretty sure the situation is improved on master (i.e. it should tell you that some manifest file is corrupt, instead of just throwing a stacktrace). `Pkg` should now be decently robust at detecting corrupt manifest files, but it would be better if it was explicit in this case that the corrupt manifest file comes from the git history.

> One that just tells you the current state of everything

@oxinabox You are referring to just pretty printing the project/manifest files, correct?

**Comment by oxinabox** [comment]
correct
