### ISSUE TITLE
getting WebExceptions on 1.5 rc1

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/Pkg.jl#1892]
Disclaimer: I'm on Windows 10 Pro 😆
```julia
(@v1.5) pkg> add Makie
   Updating registry at `C:\Users\Aaron\.julia\registries\General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
Downloading artifact: libvorbis
Ausnahme beim Aufrufen von "DownloadFile" mit 2 Argument(en):  "Der Remoteserver hat einen Fehler zurückgegeben: (504)
Gatewaytimeout."
In Zeile:15 Zeichen:1
+ $webclient.DownloadFile("https://pkg.julialang.org/artifact/a934706fd ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```
as the error is printed in German I guess that it not necessarily is the fault of Julia but I don't have any clue how to solve it failing to download an artifact :/
It happens at literally all artifacts.

**Comment by KristofferC** [comment]
What happens if you do `ENV["JULIA_PKG_SERVER"] = ""`.

**Comment by rapus95** [comment]
Since I first couldn't repoduce it I deleted the whole .julia directory (was a clean install so nothing is lost) and started over again.
This one seems to be the first problem:
```julia
(@v1.5) pkg> add Makie
 Installing known registries into `C:\Users\Aaron\.julia`
[ Info: LEGAL NOTICE: package operations send anonymous data about your system to [...]
┌ Warning: could not download https://pkg.julialang.org/registries
└ @ Pkg.Types D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Types.jl:951
┌ Warning: could not download https://pkg.julialang.org/registries
└ @ Pkg.Types D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Types.jl:951
    Cloning registry from "https://github.com/JuliaRegistries/General.git"
```
I'll try with changed ENV soon.

**Comment by KristofferC** [comment]
No, that's why you could try without the Pkg server

**Comment by rapus95** [comment]
Well yeah, w/o the pkg server it works w/o warnings. Is the problem with the pkg server on my end or Julia Computings end? I.e. is there anything I have to do to follow the progress towards the pkg protocol?

**Comment by KristofferC** [comment]
It should just work... Cc @staticfloat

**Comment by rapus95** [comment]
I once again removed the whole .julia directory and for now it seems to work flawlessly (and a lot faster) over the pkg server (than via git).

**Comment by rapus95** [comment]
```julia
(@v1.5) pkg> add CSV
   Updating registry at `C:\Users\Aaron\.julia\registries\General`
┌ Warning: could not download https://pkg.julialang.org/registries
└ @ Pkg.Types D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Types.jl:951
  Resolving package versions...
```
Again seems to have problems :/

**Comment by staticfloat** [comment]
I'm assuming you're in the EU?  We had some issues with the EU server a few days ago; can you try again now?

**Comment by rapus95** [comment]
For me it redirects to https://eu-central.pkg.julialang.org/meta

**Comment by fredrikekre** [comment]
> Could we make such an uptime graph like those on github status?

https://staging.fredrikekre.se/

**Comment by rapus95** [comment]
> https://staging.fredrikekre.se/

Is that a new one? And is there any official announcement of that dashboard? Bcs I guess not many people know about it :D Are there plans to move it to julialang.org?

I'm a little concerned that it doesn't show any issues in the last days (in constrast to what @staticfloat said)

**Comment by rapus95** [comment]
For a cold start (renamed .julia to something else in order to simulate a clean install) I've got that timing:
```julia
julia> using Pkg

julia> @time Pkg.add("ImageMagick")
 Installing known registries into `C:\Users\Aaron\.julia`
[ Info: LEGAL NOTICE: package operations send anonymous data about your system to https://pkg.julialang.org (your current package server), including the operating system and Julia versions you are using, and a random client UUID. Running `Pkg.telemetryinfo()` will show exactly what data is sent. See https://julialang.org/legal/data/ for more details about what this data is used for, how long it is retained, and how to opt out of sending it.
      Added registry `General` to `C:\Users\Aaron\.julia\registries\General`
  Resolving package versions...
  Installed Zstd_jll ────────── v1.4.5+0
  Installed PaddedViews ─────── v0.5.5
  Installed Reexport ────────── v0.2.0
  Installed ImageMagick_jll ─── v6.9.10-12+3
  Installed ImageMagick ─────── v1.1.5
  Installed Colors ──────────── v0.12.3
  Installed FileIO ──────────── v1.3.0
┌ Info: Replacing symlinks in tarball by their source files ...
└ "docs\\src\\LICENSE.md" => "docs\\src\\../../LICENSE.md"
  Installed ImageCore ───────── v0.8.14
  Installed JpegTurbo_jll ───── v2.0.1+1
  Installed Libtiff_jll ─────── v4.1.0+0
  Installed Zlib_jll ────────── v1.2.11+14
  Installed MosaicViews ─────── v0.2.2
  Installed NaNMath ─────────── v0.3.3
  Installed OffsetArrays ────── v1.1.1
  Installed libpng_jll ──────── v1.6.37+3
  Installed Requires ────────── v1.0.1
  Installed MappedArrays ────── v0.2.2
  Installed Graphics ────────── v1.0.2
  Installed FixedPointNumbers ─ v0.8.1
  Installed ColorTypes ──────── v0.10.6
Updating `C:\Users\Aaron\.julia\environments\v1.5\Project.toml`
  [6218d12a] + ImageMagick v1.1.5
Updating `C:\Users\Aaron\.julia\environments\v1.5\Manifest.toml`
  [3da002f7] + ColorTypes v0.10.6
  [5ae59095] + Colors v0.12.3
  [5789e2e9] + FileIO v1.3.0
  [53c48c17] + FixedPointNumbers v0.8.1
  [a2bd30eb] + Graphics v1.0.2
  [a09fc81d] + ImageCore v0.8.14
  [6218d12a] + ImageMagick v1.1.5
  [c73af94c] + ImageMagick_jll v6.9.10-12+3
  [aacddb02] + JpegTurbo_jll v2.0.1+1
  [89763e89] + Libtiff_jll v4.1.0+0
  [dbb5928d] + MappedArrays v0.2.2
  [e94cdb99] + MosaicViews v0.2.2
  [77ba4419] + NaNMath v0.3.3
  [6fe1bfb0] + OffsetArrays v1.1.1
  [5432bcbf] + PaddedViews v0.5.5
  [189a3867] + Reexport v0.2.0
  [ae029012] + Requires v1.0.1
  [83775a58] + Zlib_jll v1.2.11+14
  [3161d3a3] + Zstd_jll v1.4.5+0
  [b53b4c65] + libpng_jll v1.6.37+3
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
 79.799722 seconds (8.45 M allocations: 500.579 MiB, 0.16% gc time)
```

I.e. almost 80 seconds, is that a normal time for cloning the registry and downloading those libraries? Because for 50 of those seconds my internet has been used for less than 10kb/s).

**Comment by fredrikekre** [comment]
> Is that a new one? And is there any official announcement of that dashboard? Bcs I guess not many people know about it :D Are there plans to move it to julialang.org?

Yea I created it right now (hence no record of failure), and yes we are moving it to julialang.org.

**Comment by KristofferC** [comment]
> is that a normal time for cloning the registry and downloading those libraries?

no

**Comment by rapus95** [comment]
> Yea I created it right now (hence no record of failure), and yes we are moving it to julialang.org.

Nice!!

> no

Damn, I repeated it, again 79.2 secs :/

**Comment by stillyslalom** [comment]
I'm seeing a similar issue with CUDA.jl artifacts:
```
julia> using CUDA, Pkg.Artifacts

julia> artifact_toml = joinpath(pkgdir(CUDA), "Artifacts.toml")
"C:\\Users\\alexa\\.julia\\packages\\CUDA\\YU1DS\\Artifacts.toml"

julia> ensure_artifact_installed("CUDA110", artifact_toml)
Downloading artifact: CUDA110
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (502) Bad Gateway."
At line:12 char:1
+ $webclient.DownloadFile("https://pkg.julialang.org/artifact/4747fe73a ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
"C:\\Users\\alexa\\.julia\\artifacts\\4747fe73a29e16337cb33702edae26b4e681ae52"

julia> artifact_hash("CUDA110", artifact_toml) |> verify_artifact
false
```
At this point I deleted the artifact folder and tried [this](https://github.com/JuliaLang/Pkg.jl/issues/1892#issuecomment-651885619) suggestion. No exceptions were thrown, but the artifact is still bad:
```
julia> ENV["JULIA_PKG_SERVER"] = ""
""

julia> ensure_artifact_installed("CUDA110", artifact_toml)
"C:\\Users\\alexa\\.julia\\artifacts\\4747fe73a29e16337cb33702edae26b4e681ae52"

julia> artifact_hash("CUDA110", artifact_toml) |> verify_artifact
false
```

**Comment by staticfloat** [comment]
`verify_artifact()` unfortunately probably won't work on Windows, due to filesystem permissions issues.  I would just manually look in `C:\\Users\\alexa\\.julia\\artifacts\\4747fe73a29e16337cb33702edae26b4e681ae52` and if it looks reasonable and doesn't throw any errors when you try to load it, it should be fine.

In Julia 1.6 we'll have an alternate way of installing that will be more foolproof on Windows; sorry for the issues you're experiencing!

**Comment by stillyslalom** [comment]
The problem is that it *does* throw errors when I try to load it. `verify_artifact` worked for another CUDA artifact, so it's not completely broken. I can manually download the other CUDA artifact:
```
julia> download("https://us-east.pkg.julialang.org/artifact/804435c7dbe9d002d6caa0a8b3596d11a6faa778")
"C:\\Users\\alexa\\AppData\\Local\\Temp\\jl_6zFkBqvIdg"
```
...but not the failed one
```
julia> download("https://us-east.pkg.julialang.org/artifact/4747fe73a29e16337cb33702edae26b4e681ae52")
┌ Error: Download failed: curl: (22) The requested URL returned error: 502 Bad Gateway
└ @ Base download.jl:43
ERROR: failed process: Process(`'C:\WINDOWS\System32\curl.exe' -s -S -g -L -f -o 'C:\Users\alexa\AppData\Local\Temp\jl_cKeJE98lD5' https://us-east.pkg.julialang.org/artifact/4747fe73a29e16337cb33702edae26b4e681ae52`, ProcessExited(22)) [22]
```

**Comment by maleadt** [comment]
I'm getting gateway timeouts as well all the time, even though status.julialang.org claims all services are running. For example, one of the CUDNN artifacts I'm currently working on (`curl` invocation reproduced from what Julia spawned):

```
curl -H'Julia-Pkg-Protocol: 1.0' -H'Julia-Version: 1.5.0' -H'Julia-System: x86_64-linux-gnu-libgfortran4-cxx11' -H'Julia-CI-Variables: APPVEYOR=n;CI=n;CI_SERVER=n;CIRCLECI=n;CONTINUOUS_INTEGRATION=n;GITHUB_ACTIONS=n;GITLAB_CI=n;JULIA_CI=n;JULIA_PKGEVAL=n;JULIA_REGISTRYCI_AUTOMERGE=n;TF_BUILD=n;TRAVIS=n' -H'Julia-Interactive: true' -L https://pkg.julialang.org/artifact/88dc9adaa9ab5841c6d61f4cb3105ebacd95b95d   
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   167  100   167    0     0      2      0  0:01:23  0:01:00  0:00:23    43
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.19.0</center>
</body>
</html>
```

This is the eu-central server:

```
> GET /artifact/88dc9adaa9ab5841c6d61f4cb3105ebacd95b95d HTTP/1.1
> Host: eu-central.pkg.julialang.org
> User-Agent: curl/7.71.1
> Accept: */*
> Julia-Pkg-Protocol: 1.0
> Julia-Version: 1.5.0
> Julia-System: x86_64-linux-gnu-libgfortran4-cxx11
> Julia-CI-Variables: APPVEYOR=n;CI=n;CI_SERVER=n;CIRCLECI=n;CONTINUOUS_INTEGRATION=n;GITHUB_ACTIONS=n;GITLAB_CI=n;JULIA_CI=n;JULIA_PKGEVAL=n;JULIA_REGISTRYCI_AUTOMERGE=n;TF_BUILD=n;TRAVIS=n
> Julia-Interactive: true
> 
  0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:--:--     0{ [5 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 504 Gateway Time-out
< Server: nginx/1.19.0
< Date: Fri, 07 Aug 2020 09:29:16 GMT
< Content-Type: text/html
< Content-Length: 167
< Connection: keep-alive
< 
{ [167 bytes data]
100   167  100   167    0     0      2      0  0:01:23  0:01:00  0:00:23    43
* Connection #1 to host eu-central.pkg.julialang.org left intact
```

**Comment by stillyslalom** [comment]
Is there any evidence of these failed downloads in the server logs?

**Comment by stillyslalom** [comment]
Copy-pasting @staticfloat's explanation on Slack so it doesn't get lost:

> I think I’ve figured it out; I think the issue is that your artifacts are large enough that when we’re doing the tarball hashing, our BufferStreams between the `gzip -d` process and the `Tar.tree_hash` Task inflate up to very large sizes
> 
> So I’m adding back-pressure to pause the `gzip` process when the intermediate pipe gets full, so that it doesn’t consume all available memory

**Comment by HenriDeh** [comment]
Is there a fix or a workaround for this ? I can't work since this issue appeared.

**Comment by stillyslalom** [comment]
@HenriDeh Have you tried downloading the CUDA libraries corresponding to your graphics driver version directly from Nvidia? https://developer.nvidia.com/cuda-toolkit-archive

**Comment by maleadt** [comment]
> @HenriDeh Have you tried downloading the CUDA libraries corresponding to your graphics driver version directly from Nvidia? https://developer.nvidia.com/cuda-toolkit-archive

This is obviously not a solution, the whole artifact system exists to avoid that.

@HenriDeh Try running with `JULIA_PKG_SERVER=` (i.e. set to an empty string).

**Comment by HenriDeh** [comment]
I can't reproduce the error to try your fix. Since I solve [this one](https://github.com/JuliaGPU/CUDA.jl/issues/355) everything is back to normal.

**Comment by Roger-luo** [comment]
I got this on 1.5.2 as well, I'm in Waterloo, Canada. directly open this in browser gives me 502 Bad Gateway at https://us-east.pkg.julialang.org/registries

**Comment by fredrikekre** [comment]
One of the two backends on https://us-east.pkg.julialang.org/registries were sad. I have rebooted them and should work now.

**Comment by storopoli** [comment]
@fredrikekre I am still having the same error with macOS Catalina

```julia
(@v1.5) pkg> up
   Updating registry at `~/.julia/registries/General`
┌ Warning: could not download https://pkg.julialang.org/registries
└ @ Pkg.Types /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Types.jl:951
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
```

**Comment by KristofferC** [comment]
Doesn't seem like something addressable by Pkg.jl.
