### ISSUE TITLE
Unable to add unregistered packages on macOS Monterey

### ISSUE THREAD

**Issue by Samuel3008** [JuliaLang/Pkg.jl#2788]
Hi,

I'm unable to add unregistered packages (registered ones work just fine).

Specifically to test this issue, I started Julia with a new depot (`export JULIA_DEPOT_PATH=/Users/samuel/tmp`) and the first time I try to add an unregistered package, I get the below output followed by Julia crashing.
```
(@v1.6) pkg> add https://github.com/JuliaLang/Example.jl
     Cloning git-repo `https://github.com/JuliaLang/Example.jl`

signal (10): Bus error: 10
in expression starting at none:0
jl_system_image_data at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
Allocations: 2649 (Pool: 2640; Big: 9); GC: 0
zsh: bus error  julia
```

After restarting Julia, the result changes to
```
(@v1.6) pkg> add https://github.com/JuliaLang/Example.jl
ERROR: GitError(Code:ENOTFOUND, Class:Repository, could not find repository from '/Users/samuel/tmp/clones/15037770950778237535')
Stacktrace:
  [1] macro expansion
    @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LibGit2/src/error.jl:110 [inlined]
  [2] LibGit2.GitRepo(path::String)
    @ LibGit2 /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LibGit2/src/repository.jl:11
  [3] #ensure_clone#2
    @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/GitTools.jl:70 [inlined]
  [4] handle_repo_add!(ctx::Pkg.Types.Context, pkg::Pkg.Types.PackageSpec)
    @ Pkg.Types /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:640
  [5] handle_repos_add!(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.Types /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:707
  [6] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Iterators.Pairs{Symbol, Base.TTY, Tuple{Symbol}, NamedTuple{(:io,), Tuple{Base.TTY}}})
    @ Pkg.API /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:184
  [7] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:80
  [8] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:78
  [9] do_cmd!(command::Pkg.REPLMode.Command, repl::REPL.LineEditREPL)
    @ Pkg.REPLMode /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:408
 [10] do_cmd(repl::REPL.LineEditREPL, input::String; do_rethrow::Bool)
    @ Pkg.REPLMode /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:386
 [11] do_cmd
    @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:377 [inlined]
 [12] (::Pkg.REPLMode.var"#24#27"{REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::IOBuffer, ok::Bool)
    @ Pkg.REPLMode /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:550
 [13] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [14] invokelatest
    @ ./essentials.jl:706 [inlined]
 [15] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/REPL/src/LineEdit.jl:2441
 [16] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:1126
 [17] (::REPL.var"#44#49"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ./task.jl:411
```
and Julia no longer crashes. The same thing happens on master.

```
julia> versioninfo()
Julia Version 1.6.3
Commit ae8452a9e0 (2021-09-23 17:34 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 6
  JULIA_DEPOT_PATH = /Users/samuel/tmp
```
Note that I'm on the current dev beta of macOS Monterey (21A558).

**Comment by Samuel3008** [comment]
> I meant if you have access to a previous non-beta version on the same machine.

Oops seems obvious in hindsight! I don't, unfortunately, though :/

> But it's okay if you don't, we'll do our best to debug it nevertheless.

Great, thank you!

So, after modifying your command slightly, this is what I got:
```
~                                                                                                  
❯ export JULIA_DEPOT_PATH=$(mktemp -d)

~                                                                                                  
❯ lldb -- /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia -e 'import Pkg; Pkg.add(url="https://github.com/JuliaLang/Example.jl")'
(lldb) target create "/Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia"
Current executable set to '/Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia' (x86_64).
(lldb) settings set -- target.run-args  "-e" "import Pkg; Pkg.add(url=\"https://github.com/JuliaLang/Example.jl\")"
(lldb) process launch
Process 70484 launched: '/Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia' (x86_64)
     Cloning git-repo `https://github.com/JuliaLang/Example.jl`
Process 70484 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x113b09000)
    frame #0: 0x0000000113b09000 sys.dylib`jl_system_image_data + 142464
sys.dylib`jl_system_image_data:
->  0x113b09000 <+142464>: addb   %al, (%rax)
    0x113b09002 <+142466>: addb   %al, (%rax)
    0x113b09004 <+142468>: addb   %al, (%rax)
    0x113b09006 <+142470>: addb   %al, (%rax)
Target 0: (julia) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x113b09000)
  * frame #0: 0x0000000113b09000 sys.dylib`jl_system_image_data + 142464
    frame #1: 0x000000011231f7a2 libgit2.1.3.0.dylib`git__clone + 252
    frame #2: 0x0000000112fb9f6f sys.dylib`julia_clone_54590.clone_1 at error.jl:108
    frame #3: 0x00000001138a9516 sys.dylib`julia_YY.cloneYY.122_54482.clone_1.clone_2 at LibGit2.jl:583
    frame #4: 0x00000001138a79e7 sys.dylib`julia_YY.cloneYY.3_51986.clone_1.clone_2 at LibGit2.jl:562
    frame #5: 0x000000011388b3e3 sys.dylib`julia_handle_repo_addNOT._48558.clone_1.clone_2 at GitTools.jl:87
    frame #6: 0x0000000113550b03 sys.dylib`japi1_handle_repos_addNOT._48741.clone_1.clone_2 at Types.jl:707
    frame #7: 0x000000011368895d sys.dylib`julia_YY.addYY.95_50233.clone_1.clone_2 at API.jl:184
    frame #8: 0x0000000113183e93 sys.dylib`julia_addYY.YY.kw_50111.clone_1 at API.jl:155
    frame #9: 0x0000000113183f00 sys.dylib`jfptr_addYY.YY.kw_50112.clone_1 + 80
    frame #10: 0x0000000101ce0fc0 libjulia-internal.1.6.dylib`jl_apply_generic + 1920
    frame #11: 0x00000001131d6990 sys.dylib`japi1_YY.addYY.24_50664.clone_1 at API.jl:80
    frame #12: 0x0000000101ce0fc0 libjulia-internal.1.6.dylib`jl_apply_generic + 1920
    frame #13: 0x0000000113169025 sys.dylib`japi1_add_50766.clone_1 at API.jl:78
    frame #14: 0x0000000111b13608
    frame #15: 0x0000000111b13742
    frame #16: 0x0000000101cf8260 libjulia-internal.1.6.dylib`do_call + 208
    frame #17: 0x0000000101cf6b95 libjulia-internal.1.6.dylib`eval_body + 1333
    frame #18: 0x0000000101cf6f0d libjulia-internal.1.6.dylib`jl_interpret_toplevel_thunk + 269
    frame #19: 0x0000000101d11845 libjulia-internal.1.6.dylib`jl_toplevel_eval_flex + 6165
    frame #20: 0x0000000101d11605 libjulia-internal.1.6.dylib`jl_toplevel_eval_flex + 5589
    frame #21: 0x0000000101d11605 libjulia-internal.1.6.dylib`jl_toplevel_eval_flex + 5589
    frame #22: 0x0000000101d12135 libjulia-internal.1.6.dylib`jl_toplevel_eval_in + 149
    frame #23: 0x000000011354d46c sys.dylib`julia_exec_options_39185.clone_1.clone_2 at boot.jl:360
    frame #24: 0x0000000112f8551b sys.dylib`julia__start_31087.clone_1 at client.jl:485
    frame #25: 0x0000000112f85676 sys.dylib`jfptr__start_31088.clone_1 + 6
    frame #26: 0x0000000101ce0fc0 libjulia-internal.1.6.dylib`jl_apply_generic + 1920
    frame #27: 0x0000000101d31133 libjulia-internal.1.6.dylib`true_main + 179
    frame #28: 0x0000000101d31024 libjulia-internal.1.6.dylib`repl_entrypoint + 164
    frame #29: 0x0000000100000f79 julia`main + 9
    frame #30: 0x000000010000c4fe dyld`start + 462
(lldb) 
```
Doesn't tell me anything tbh, but I'm hoping it's helpful?

**Comment by staticfloat** [comment]
What happens if you run:

```
julia> using LibGit2
       dir = mktempdir()
       LibGit2.clone("https://github.com/JuliaLang/Example.jl", dir)
LibGit2.GitRepo("/private/var/folders/0d/9vhfkswj7lb8smj9_p4hjnrh0000gn/T/jl_Ep3ZH0")
```

**Comment by Samuel3008** [comment]
Same thing as before:
```
julia> using LibGit2

julia> dir = mktempdir()
"/var/folders/3d/g_t6f_0d6vjf31l8slt24lt00000gn/T/jl_8uTO19"

julia> LibGit2.clone("https://github.com/JuliaLang/Example.jl", dir)

signal (10): Bus error: 10
in expression starting at REPL[3]:1
jl_system_image_data at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
Allocations: 2649 (Pool: 2640; Big: 9); GC: 0
zsh: bus error  julia
```

**Comment by fredrikekre** [comment]
Maybe fixed by https://github.com/JuliaLang/julia/pull/42721?

**Comment by Samuel3008** [comment]
I just tried on the nightly build and it still doesn't work, unfortunately.

**Comment by staticfloat** [comment]
When you start up the nightly, can you verify, using the dllist() function from the Libdl module, that no libraries are coming from /usr/local/?

**Comment by Samuel3008** [comment]
```
~ ❯ julia-nightly
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV.915 (2021-11-08)
 _/ |\__'_|_|_|\__'_|  |  Commit e3b9290e0c (0 days old master)
|__/                   |

julia> using Libdl

julia> any(lib -> occursin("/usr/local", lib), dllist())
false
```

**Comment by Samuel3008** [comment]
Just upgraded to 1.6.4 and this issue seems fixed.

**Comment by KristofferC** [comment]
Could you check https://github.com/JuliaLang/Pkg.jl/issues/2788#issuecomment-963287840 again?

**Comment by Samuel3008** [comment]
Sure! I tried on both 1.6.4 and the current master, but the result hasn't changed: There's no libraries loaded from /usr/local.

**Comment by KristofferC** [comment]
@staticfloat, any idea here?

**Comment by staticfloat** [comment]
No; I haven't been able to reproduce this error on any other machine, unfortunately.  :(

**Comment by Samuel3008** [comment]
I did a fresh install with 1.7 and it seems to work now! Thanks everybody!

**Comment by adamhsparks** [comment]
I see that this is closed, but I'm getting the same on macOS Monterey 1.7.1 as well now. I've done a fresh install to be sure.

```julia
julia> using Pkg

julia> add https://github.com/JuliaLang/Example.jl
ERROR: syntax: extra token "https" after end of expression
Stacktrace:
 [1] top-level scope
   @ none:1
```

Version info

```julia
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.2.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
```

**Comment by Samuel3008** [comment]
You need to enter `Pkg` mode by typing `]` in the REPL, only then can you do `add https://github.com/JuliaLang/Example.jl`.

**Comment by adamhsparks** [comment]
OK, but that doesn't work either.

```julia
(@v1.7) pkg> add https://github.com/JuliaLang/Example.jl
ERROR: GitError(Code:ENOTFOUND, Class:Repository, could not find repository from '/Users/adamsparks/.julia/clones/15037770950778237535')
Stacktrace:
  [1] macro expansion
    @ /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LibGit2/src/error.jl:110 [inlined]
  [2] LibGit2.GitRepo(path::String)
    @ LibGit2 /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LibGit2/src/repository.jl:11
  [3] #ensure_clone#2
    @ /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Pkg/src/GitTools.jl:72 [inlined]
  [4] handle_repo_add!(ctx::Pkg.Types.Context, pkg::Pkg.Types.PackageSpec)
    @ Pkg.Types /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Pkg/src/Types.jl:676
  [5] handle_repos_add!(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.Types /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Pkg/src/Types.jl:743
  [6] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Pairs{Symbol, Base.TTY, Tuple{Symbol}, NamedTuple{(:io,), Tuple{Base.TTY}}})
    @ Pkg.API /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Pkg/src/API.jl:248
  [7] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Pkg/src/API.jl:149
  [8] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Pkg/src/API.jl:144
  [9] do_cmd!(command::Pkg.REPLMode.Command, repl::REPL.LineEditREPL)
    @ Pkg.REPLMode /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Pkg/src/REPLMode/REPLMode.jl:407
 [10] do_cmd(repl::REPL.LineEditREPL, input::String; do_rethrow::Bool)
    @ Pkg.REPLMode /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Pkg/src/REPLMode/REPLMode.jl:385
 [11] do_cmd
    @ /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Pkg/src/REPLMode/REPLMode.jl:376 [inlined]
 [12] (::Pkg.REPLMode.var"#24#27"{REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::IOBuffer, ok::Bool)
    @ Pkg.REPLMode /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Pkg/src/REPLMode/REPLMode.jl:549
 [13] #invokelatest#2
    @ ./essentials.jl:716 [inlined]
 [14] invokelatest
    @ ./essentials.jl:714 [inlined]
 [15] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/REPL/src/LineEdit.jl:2493
 [16] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/REPL/src/REPL.jl:1230
 [17] (::REPL.var"#49#54"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ./task.jl:423

(@v1.7) pkg> 
```
