### ISSUE TITLE
"can not merge projects" on dev dependency in ./test

### ISSUE THREAD

**Issue by gustafsson** [JuliaLang/Pkg.jl#3410]
When a `./test` folder has a dev dependency which shares a dependency with the project under test I get this error:

```julia
julia> Pkg.test()
  Activating project at `~/JuliaTestDev/MyProgram/test`
  No Changes to `~/JuliaTestDev/MyProgram/test/Project.toml`
  No Changes to `~/JuliaTestDev/MyProgram/test/Manifest.toml`
  Activating project at `~/JuliaTestDev/MyProgram`
     Testing MyProgram
ERROR: can not merge projects
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Pkg/src/Types.jl:68
```

The error can be reproduced by running this script in an empty folder:
```julia
import Pkg

somestdlib = "Base64"

Pkg.generate("MyTestSupport")
Pkg.activate("MyTestSupport")
Pkg.add(somestdlib)

Pkg.generate("MyProject")
Pkg.activate("MyProject/test")
Pkg.develop(path="./MyTestSupport")
touch("MyProject/test/runtests.jl")

Pkg.activate("MyProject")
Pkg.test() # MyProject tests passed 

Pkg.add(somestdlib)
Pkg.test() # ERROR: can not merge projects
```

---

I installed Julia with https://julialang-s3.julialang.org/bin/mac/x64/1.9/julia-1.9.0-rc1-mac64.dmg
```julia
julia> versioninfo()
Julia Version 1.9.0-rc1
Commit 3b2e0d8fbc1 (2023-03-07 07:51 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 8 × Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, ivybridge)
  Threads: 1 on 8 virtual cores
```

**Comment by Seelengrab** [comment]
I think this is fixed by https://github.com/JuliaLang/Pkg.jl/pull/3276

**Comment by IanButterworth** [comment]
julia nightly has that fix now. Please reopen if you find it's not fixed there

**Comment by bgroenks96** [comment]
Is this going to be backported into 1.9?

The latest stable version 1.9.3 seems to still have this issue.

**Comment by freemin7** [comment]
As does 1.9.4 i think.

**Comment by gustafsson** [comment]
Seems the fix didn't make it into Julia 1.10.0 where I still get `ERROR: can not merge projects` with the reproduction script above.

Julia Nightly however handles the reproduction script just fine.

**Comment by freemin7** [comment]
Really? 
_much sad_
