### ISSUE TITLE
Adding Github repo does not add `[sources]` section in Project.toml

### ISSUE THREAD

**Issue by mitiemann** [JuliaLang/Pkg.jl#4124]
Adding a Github repo does not add an `[sources]` entry in the Project.toml, leading to an unhelpful error message. This happens both in Pkg REPL mode and in API mode.

MWE:
```shell
mkdir {A,B}
cd A
julia -e 'import Pkg; Pkg.activate("."); Pkg.add(url="https://github.com/tlienart/Xranklin.jl.git")'
cd ../B
cp ../A/Project.toml .
julia --project=@. -e 'import Pkg; Pkg.instantiate()'
```
throws a `pkgerror`:
```
ERROR: expected package `Xranklin [558449b0]` to be registered
```

**Comment by jakobnissen** [comment]
Discussed in https://github.com/JuliaLang/Pkg.jl/pull/3826 and https://github.com/JuliaLang/Pkg.jl/pull/3783#issuecomment-1971225694

**Comment by mitiemann** [comment]
Thanks! Is there anything that I could help with to move #3826 forwards?

**Comment by KristofferC** [comment]
This should be fixed via https://github.com/JuliaLang/Pkg.jl/pull/4225

**Comment by RomeoV** [comment]
This issue is still occuring for me as of julia 1.11.7 and 1.12.1. More specifically, running exactly the example in the original post still fails, and no [sources] section shows up.

**Comment by KristofferC** [comment]
It is only available in 1.13.
