### ISSUE TITLE
Devving packages does not work on terminal emulator kitty

### ISSUE THREAD

**Issue by piever** [JuliaLang/Pkg.jl#787]
Even though Pkg works smoothly on the default gnome terminal, it fails to develop packages locally on [Kitty](https://github.com/kovidgoyal/kitty).

Here's what I get:

```julia
(v1.0) pkg> dev StructArrays
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
┌ Warning: Some registries failed to update:
│     — /home/pietro/.julia/registries/General — failed to fetch from repo
└ @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:144
  Updating git-repo `https://github.com/piever/StructArrays.jl.git`
ERROR: failed to fetch from https://github.com/piever/StructArrays.jl.git, error: GitError(Code:ECERTIFICATE, Class:SSL, the SSL certificate is invalid: 0x08 - The certificate is not correctly signed by the trusted CA)
```

However on Kitty I have no problem cloning the repository normally:

```
$ git clone https://github.com/piever/StructArrays.jl.git
Cloning into 'StructArrays.jl'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 222 (delta 0), reused 1 (delta 0), pack-reused 218
Receiving objects: 100% (222/222), 35.90 KiB | 140.00 KiB/s, done.
Resolving deltas: 100% (120/120), done.
```

I'm not sure whether the problem should be fixed on Pkg side or on Kitty side but I thought it was relevant to report it here.

**Comment by piever** [comment]
Closing as the problem is fixed on the Julia 1.0.2 release branch.

**Comment by xukai92** [comment]
@piever I still got this problem with Julia 1.0.2. Any idea how do you solve it?

**Comment by xukai92** [comment]
Also this only happens to my Ubuntu machine; my macOS with kitty works fine.

**Comment by piever** [comment]
I'm on ubuntu and actually I shouldn't have closed the issue: it seemed fixed at some point when I was using Julia built from source (on the 1.0.2 release branch) but the problem started popping up again. Not sure if it was a fluke or if building from source makes a difference.

**Comment by ziotom78** [comment]
I confirm that this is still happening with Julia 1.1.1: running `] up` in a Kitty terminal fails with SSL errors, but running the same in GNOME Terminal works fine.

**Comment by KristofferC** [comment]
Doesn't really look like something Pkg can do anything about. FWIW, I use Kitty myself and have no problems using Pkg.
